service: ec2-instance-manager

provider:
  name: aws
  runtime: python3.7
  stage: dev
  stackName: ec2-instance-manager-stack
  apiName: ec2-instance-manager-gw
  deploymentBucket:
    tags: 
      profile: automation
  role: arn:aws:iam::212568053769:role/role-lambda-start-stop-ec2

package:
  individually: true
  exclude:
    - ec2/**
    - README.md
    - resources/**
  mode: 644

functions:
  start:
    handler: src/start.start
    environment:
      region: 'us-east-1'
      rds: 'boomcredit-dev-cluster boomcredit-qa-cluster'
      stack_params: '{"Params":[{"name":"ecs-spot-dev-cluster","template_url":"https://boomcredit-devops.s3.amazonaws.com/cloudformation-templates/ecs-spot-cluster/ecs-spot-dev-cluster.yml"},{"name":"ecs-spot-qa-cluster","template_url":"https://boomcredit-devops.s3.amazonaws.com/cloudformation-templates/ecs-spot-cluster/ecs-spot-qa-cluster.yml"}]}'
    package:
      include:
        - src/start.py
      exclude:
        - src/**
        - resources/**
      mode: 644
    events:
      - http:
          path: /start
          method: get

  stop:
    handler: src/stop.stop
    environment:
      region: 'us-east-1'
      rds: 'boomcredit-dev-cluster boomcredit-qa-cluster'
      stack_params: '{"Params":[{"name":"ecs-spot-dev-cluster","template_url":"https://boomcredit-devops.s3.amazonaws.com/cloudformation-templates/ecs-spot-cluster/ecs-spot-dev-cluster.yml"},{"name":"ecs-spot-qa-cluster","template_url":"https://boomcredit-devops.s3.amazonaws.com/cloudformation-templates/ecs-spot-cluster/ecs-spot-qa-cluster.yml"}]}'
    package:
      include:
        - src/stop.py
      exclude:
        - src/**
        - resources/**
      mode: 644
    events:
      - http:
          path: /stop
          method: get

  change:
    handler: src/change.change
    environment:
      region: 'us-east-1'
      instances: 'i-008e6ffb96239b1e5 i-0da218f6da5cecbc1 i-0fb50980cc23f9bd2'
      rds: 'boomcredit-dev-cluster boomcredit-qa-cluster'
      start_event: 'StartEC2instances'
      stop_event: 'StopEC2instances'
      slack_token: 'xoxb-293645508629-622608232563-wAbR7cJykuFzZkYd25OuzZfY'
      channel : '%23aws'  
    package:
      include:
        - src/change.py
      exclude:
        - src/**
        - resources/**
      mode: 644
    events:
      - http:
          path: /change
          method: put

