service: ec2-instance-manager

provider:
  name: aws
  runtime: python3.7
  stage: dev
  stackName: ec2-instance-manager-stack
  apiName: ec2-instance-manager-gw
  deploymentBucket:
    tags: 
      profile: automation
  role: arn:aws:iam::776449101057:role/role-lambda-start-stop-ec2

package:
  individually: true
  exclude:
    - ec2/**
    - README.md
    - node_modules/**
  mode: 644

functions:
  start:
    handler: src/start.start
    environment:
      region: 'us-east-1'
      stack_params: '{"Params":[{"name":"ecs-spot-demo-cluster","template_url":"https://demo-user-group-cf.s3.amazonaws.com/demo.yml"}]}'
    package:
      include:
        - src/start.py
      exclude:
        - src/**
        - node_modules/**
      mode: 644
    events:
      - http:
          path: /start
          method: get

  stop:
    handler: src/stop.stop
    environment:
      region: 'us-east-1'
      stack_params: '{"Params":[{"name":"ecs-spot-demo-cluster","template_url":"https://demo-user-group-cf.s3.amazonaws.com/demo.yml"}]}'
    package:
      include:
        - src/stop.py
      exclude:
        - src/**
        - node_modules/**
      mode: 644
    events:
      - http:
          path: /stop
          method: get

  change:
    handler: src/change.change
    environment:
      region: 'us-east-1'
      start_event: 'StartEC2instances'
      stop_event: 'StopEC2instances'
      slack_token: 'xoxb-293645508629-622608232563-wAbR7cJykuFzZkYd25OuzZfY'
      channel : '%23aws'  
    package:
      include:
        - src/change.py
      exclude:
        - src/**
        - node_modules/**
      mode: 644
    events:
      - http:
          path: /change
          method: put

